// Scan issues/*.html and (re)generate src/issues.index.js — the static manifest
// the Worker imports: newest-first list of { date, published, repos[], html }.
// Run after adding or editing any issue.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { extractRepos } from './lib-tagstars.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const issuesDir = join(here, '..', 'issues');
const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];

function publishedLabel(date) {
  const [y, m, d] = date.split('-').map(Number);
  return `${MONTHS[m - 1]} ${d}, ${y}`;
}

const dates = readdirSync(issuesDir)
  .filter((f) => /^\d{4}-\d{2}-\d{2}\.html$/.test(f))
  .map((f) => f.replace('.html', ''))
  .sort()
  .reverse(); // newest first

const entries = dates.map((date) => {
  const html = readFileSync(join(issuesDir, `${date}.html`), 'utf8');
  return { date, published: publishedLabel(date), repos: extractRepos(html) };
});

const ident = (d) => 'html_' + d.replace(/-/g, '_');
const importLines = dates.map((d) => `import ${ident(d)} from '../issues/${d}.html';`).join('\n');
const listLines = entries
  .map((e) => `  { date: '${e.date}', published: '${e.published}', repos: ${JSON.stringify(e.repos)}, html: ${ident(e.date)} },`)
  .join('\n');

const out = `// AUTO-GENERATED by scripts/build-index.mjs — do not edit by hand.
${importLines}

export const ISSUES = [
${listLines}
];
`;

writeFileSync(join(here, '..', 'src', 'issues.index.js'), out);
console.log(`indexed ${entries.length} issue(s):`);
for (const e of entries) console.log(`  ${e.date}  (${e.published})  ${e.repos.length} repos`);
