// AUTO-GENERATED by scripts/build-index.mjs — do not edit by hand.
import html_2026_06_25 from '../issues/2026-06-25.html';

export const ISSUES = [
  { date: '2026-06-25', published: 'June 25, 2026', repos: ["calesthio/OpenMontage","DeusData/codebase-memory-mcp","google-research/timesfm","NotASithLord/peerd","altic-dev/FluidVoice","steipete/birdclaw","koala73/worldmonitor","penpot/penpot","jamiepine/voicebox","asgeirtj/system_prompts_leaks","Panniantong/Agent-Reach","ZhuLinsen/daily_stock_analysis","OpenCut-app/OpenCut"], html: html_2026_06_25 },
];
